# manual label

In [1]:
import pandas as pd

In [2]:
train = pd.read_csv ('work_bully.csv')# อ่านไฟล์ที่รวบรวมคำบูลลี่ ด้วย pandas
train

word  toxic
0        เขาออกจะ(โครต)น่ารัก เจ้าเด็กน้อยน่ารัก-///-👶💚      1
1     ใจเย็นๆนะคะ ค่อยๆรีค่ะ แจ้งเตือนเด้งรัวๆเลนตอน...      1
2     เจ้าเด็กน่ารักเกินบรรยาย!@@#$%^&*()_+-><?{}:"',.;      1
3                ฉันชอบเขามาก เขาตตรงใจเลยแกฉันรักเขา❤️      1
4     กูล่ะอย่างชอบคำว่าอะจ๊ากเลย กวนส้นตีนแบบอธิบาย...      1
...                                                 ...    ...
5395  เขาใช้รถถูกประเภทสำหรับการใช้งานแล้วครับ ตะกรร...      6
5396   ยังไม่ได้ว่าใครเป็นขยะเลย แล้วไปก๊อปข้อความใค...      6
5397  โถ.. อีสลิ่ม ดูความโง่ ของมัน  ความคิดโคตรส้นต...      6
5398  ความคิดต่ำสุดแกนโลกเลย  เอาสมองไหนมาคิดเรื่องเ...      6
5399  อนาจใจในความต่ำตมของคนพวกนี้จริงๆค่ะ รู้เลยนะค...      6

[5400 rows x 2 columns]

In [3]:

# ทำการตัดอิโมจิด้วยไลลบรารี่ re
import re

# text = 'บูม 😂'
# print(text) # with emoji
list_word=[]
for w in train['word']:
    emoji_pattern = re.compile("["
            u"\U0001F600-\U0001F64F"  # emoticons
            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
            u"\U0001F680-\U0001F6FF"  # transport & map symbols
            u"\U0001F1E0-\U0001F1FF" # flags (iOS)
            u"❤️"
            u"​"
            u"🥰"
            u"🤩"
                               "]+", flags=re.UNICODE)
    list_word.append(emoji_pattern.sub(r'', w)) # no emoji
list_word[:]

['เขาออกจะ(โครต)น่ารัก เจ้าเด็กน้อยน่ารัก-///-',
 'ใจเย็นๆนะคะ ค่อยๆรีค่ะ แจ้งเตือนเด้งรัวๆเลนตอนนี้',
 'เจ้าเด็กน่ารักเกินบรรยาย!@@#$%^&*()_+-><?{}:"\',.;',
 'ฉันชอบเขามาก เขาตตรงใจเลยแกฉันรักเขา',
 'กูล่ะอย่างชอบคำว่าอะจ๊ากเลย กวนส้นตีนแบบอธิบายไม่ได้ คอมเมดี้ไปอีกแบบจริงๆ',
 'ประเทศไทยน่าอยู่เพราะมีแหล่งธรรมชาติที่สวยงาม เราควรรักษาความสวยงานเหล่านี้ไว้',
 'อยากถูกเธอมองในเเววตาแบบนั้น อยากออยู่ในสายตาเธอบ้าง',
 'สวัสดีครับ ในรูปผมเองครับไทน์คนชิคชิค ข้างๆชื่อว่าสารวัตรเพื่อนซี้ผมเอง',
 'สวัสดีค่ะ ไม่ทราบว่ามีอะไรให้ช่วยมั้ยคะ รบกวนติดต่อinboxทีค่ะ',
 'ไงเพื่อน ไม่ได้เจอตั้งนาน หล่อขึ้นนะเนี่ยแฟนก็โครตสวยเลยว่ะ',
 'นายชื่ออะไร อยากทำความรู้จักน่ะค่ะ ถ้าไม่เป็นการรบกวนบอกได้มั้ยคะ',
 'ทำใจมีเงินพอกินพอใช้เก็บเอาเรื่อยๆ ไม่พอก็หาเพิ่ม สู้ๆนะ',
 'คิดหนักเลย นั่นก้อยากได้นี่ก้อยากได้ มีแต่ของน่าใช้ทั้งนั้นเลย',
 'พอลองแต่งตัวดูแพงแล้วสวยดูดีมากเลยแก ปังสุดเลิศหรูดูแพง ไว้ไปซื้อกันอีกนะ  ',
 'ทำไมต้องทำอย่างนั้นครับ ลองคิดดูใหม่อีกทีนะครับ ',
 'ทำแบบนี้ เห็นมั้ยง่ายกว่าแบบเมื่อกี้เยอะเลย

In [4]:
# ทำการตัดอักขระพิเศษด้วยการ replace
special = ['!','@','#','$','%','^','&','*','(',')','_','+','-','>','<','?','{','}',':', '"' ,"'", ',','.',';' , '[' , ']','/','|'  ,'=','0','1','2','3','4','5','6','7','8','9']


# x = "เจ้าเด็กน่ารักเกินบรรยาย!@#$%^&*()_+-><?{}:"
# xx= x.replace('เจ้า','sssss')
# print(xx)  


new_list = []
for w in list_word:
    for s in special:
        w = w.replace(s,'')
    new_list.append(w)
new_list

['เขาออกจะโครตน่ารัก เจ้าเด็กน้อยน่ารัก',
 'ใจเย็นๆนะคะ ค่อยๆรีค่ะ แจ้งเตือนเด้งรัวๆเลนตอนนี้',
 'เจ้าเด็กน่ารักเกินบรรยาย',
 'ฉันชอบเขามาก เขาตตรงใจเลยแกฉันรักเขา',
 'กูล่ะอย่างชอบคำว่าอะจ๊ากเลย กวนส้นตีนแบบอธิบายไม่ได้ คอมเมดี้ไปอีกแบบจริงๆ',
 'ประเทศไทยน่าอยู่เพราะมีแหล่งธรรมชาติที่สวยงาม เราควรรักษาความสวยงานเหล่านี้ไว้',
 'อยากถูกเธอมองในเเววตาแบบนั้น อยากออยู่ในสายตาเธอบ้าง',
 'สวัสดีครับ ในรูปผมเองครับไทน์คนชิคชิค ข้างๆชื่อว่าสารวัตรเพื่อนซี้ผมเอง',
 'สวัสดีค่ะ ไม่ทราบว่ามีอะไรให้ช่วยมั้ยคะ รบกวนติดต่อinboxทีค่ะ',
 'ไงเพื่อน ไม่ได้เจอตั้งนาน หล่อขึ้นนะเนี่ยแฟนก็โครตสวยเลยว่ะ',
 'นายชื่ออะไร อยากทำความรู้จักน่ะค่ะ ถ้าไม่เป็นการรบกวนบอกได้มั้ยคะ',
 'ทำใจมีเงินพอกินพอใช้เก็บเอาเรื่อยๆ ไม่พอก็หาเพิ่ม สู้ๆนะ',
 'คิดหนักเลย นั่นก้อยากได้นี่ก้อยากได้ มีแต่ของน่าใช้ทั้งนั้นเลย',
 'พอลองแต่งตัวดูแพงแล้วสวยดูดีมากเลยแก ปังสุดเลิศหรูดูแพง ไว้ไปซื้อกันอีกนะ  ',
 'ทำไมต้องทำอย่างนั้นครับ ลองคิดดูใหม่อีกทีนะครับ ',
 'ทำแบบนี้ เห็นมั้ยง่ายกว่าแบบเมื่อกี้เยอะเลย ลองทำดูกันนะ',
 'นั้นอะไรหรอ น่า

In [5]:
# ทำการแทนที่ col word ด้วย newlist ที่ตัดเอาอิโมจิกับอักขระพิเศษออก
train['word'] = new_list
train['word']

0                   เขาออกจะโครตน่ารัก เจ้าเด็กน้อยน่ารัก
1       ใจเย็นๆนะคะ ค่อยๆรีค่ะ แจ้งเตือนเด้งรัวๆเลนตอนนี้
2                                เจ้าเด็กน่ารักเกินบรรยาย
3                    ฉันชอบเขามาก เขาตตรงใจเลยแกฉันรักเขา
4       กูล่ะอย่างชอบคำว่าอะจ๊ากเลย กวนส้นตีนแบบอธิบาย...
                              ...                        
5395    เขาใช้รถถูกประเภทสำหรับการใช้งานแล้วครับ ตะกรร...
5396     ยังไม่ได้ว่าใครเป็นขยะเลย แล้วไปก๊อปข้อความใค...
5397    โถ อีสลิ่ม ดูความโง่ ของมัน  ความคิดโคตรส้นตีน...
5398    ความคิดต่ำสุดแกนโลกเลย  เอาสมองไหนมาคิดเรื่องเ...
5399    อนาจใจในความต่ำตมของคนพวกนี้จริงๆค่ะ รู้เลยนะค...
Name: word, Length: 5400, dtype: object

In [6]:
from pythainlp import word_tokenize

In [7]:
# ทำการตัดข้อความด้วย word tokenizer 
def normalizeWord(train):
    list_word = [] 
    for n in train['word'] : #วนลูปใน train โดย column เป็น "word"
            proc = word_tokenize(n, engine='newmm') #ใช้ word_tokenizer ตัดข้อความเป็นคำๆ   
            list_word.append(proc) #เก็บข้อความที่ถูกตัดออกเป็นคำๆลงไปที่ list 
    return list_word      

In [8]:
# #ex
# x = train['word'][0]
# print(x)
# kumkum = word_tokenize(x)
# kumkum

In [9]:
train['word'] = normalizeWord(train)
train['word'] # list ของข้อความที่ถูกตัดออกเป็นคำๆโดย word_tokenizer 

0       [เขา, ออกจะ, โค, รต, น่ารัก,  , เจ้า, เด็กน้อย...
1       [ใจเย็น, ๆ, นะคะ,  , ค่อยๆ, รี, ค่ะ,  , แจ้ง, ...
2                      [เจ้า, เด็ก, น่ารัก, เกิน, บรรยาย]
3       [ฉัน, ชอบ, เขา, มาก,  , เขา, ต, ตรง, ใจ, เลย, ...
4       [กู, ล่ะ, อย่าง, ชอบ, คำ, ว่า, อะ, จ๊าก, เลย, ...
                              ...                        
5395    [เขา, ใช้, รถ, ถูก, ประเภท, สำหรับ, การใช้งาน,...
5396    [ , ยัง, ไม่, ได้, ว่า, ใคร, เป็น, ขยะ, เลย,  ...
5397    [โถ,  , อี, สลิ่ม,  , ดู, ความ, โง่,  , ของ, ม...
5398    [ความคิด, ต่ำสุด, แกนโลก, เลย,   , เอา, สมอง, ...
5399    [อ, นา, จ, ใจ, ใน, ความต่ำ, ตม, ของ, คน, พวก, ...
Name: word, Length: 5400, dtype: object

In [10]:
# type(train['word'])

In [11]:
# แปลงลิสเป็นอาเรย์
train_array = train.values  #นำ list เก็บไว้ที่ array เพื่อทำการใส่ลำดับ
print(train_array[:,0])

train_array

[list(['เขา', 'ออกจะ', 'โค', 'รต', 'น่ารัก', ' ', 'เจ้า', 'เด็กน้อย', 'น่ารัก'])
 list(['ใจเย็น', 'ๆ', 'นะคะ', ' ', 'ค่อยๆ', 'รี', 'ค่ะ', ' ', 'แจ้ง', 'เตือน', 'เด้ง', 'รัว', 'ๆ', 'เลน', 'ตอนนี้'])
 list(['เจ้า', 'เด็ก', 'น่ารัก', 'เกิน', 'บรรยาย']) ...
 list(['โถ', ' ', 'อี', 'สลิ่ม', ' ', 'ดู', 'ความ', 'โง่', ' ', 'ของ', 'มัน', '  ', 'ความคิด', 'โคตร', 'ส้นตีน', ' ', 'ความคิด', 'ต่ำ', 'ๆ'])
 list(['ความคิด', 'ต่ำสุด', 'แกนโลก', 'เลย', '  ', 'เอา', 'สมอง', 'ไหน', 'มา', 'คิด', 'เรื่อง', 'เซ็กส์', 'ว่ะ', ' ', 'หรือ', 'ใน', 'หัวมัน', 'มี', 'แค่นั้น'])
 list(['อ', 'นา', 'จ', 'ใจ', 'ใน', 'ความต่ำ', 'ตม', 'ของ', 'คน', 'พวก', 'นี้', 'จริงๆ', 'ค่ะ', ' ', 'รู้', 'เลย', 'นะคะ', 'ทำไม', 'ประเทศ', 'ไทย', 'ยัง', 'ไม่', 'เจริญ'])]


array([[list(['เขา', 'ออกจะ', 'โค', 'รต', 'น่ารัก', ' ', 'เจ้า', 'เด็กน้อย', 'น่ารัก']),
        1],
       [list(['ใจเย็น', 'ๆ', 'นะคะ', ' ', 'ค่อยๆ', 'รี', 'ค่ะ', ' ', 'แจ้ง', 'เตือน', 'เด้ง', 'รัว', 'ๆ', 'เลน', 'ตอนนี้']),
        1],
       [list(['เจ้า', 'เด็ก', 'น่ารัก', 'เกิน', 'บรรยาย']), 1],
       ...,
       [list(['โถ', ' ', 'อี', 'สลิ่ม', ' ', 'ดู', 'ความ', 'โง่', ' ', 'ของ', 'มัน', '  ', 'ความคิด', 'โคตร', 'ส้นตีน', ' ', 'ความคิด', 'ต่ำ', 'ๆ']),
        6],
       [list(['ความคิด', 'ต่ำสุด', 'แกนโลก', 'เลย', '  ', 'เอา', 'สมอง', 'ไหน', 'มา', 'คิด', 'เรื่อง', 'เซ็กส์', 'ว่ะ', ' ', 'หรือ', 'ใน', 'หัวมัน', 'มี', 'แค่นั้น']),
        6],
       [list(['อ', 'นา', 'จ', 'ใจ', 'ใน', 'ความต่ำ', 'ตม', 'ของ', 'คน', 'พวก', 'นี้', 'จริงๆ', 'ค่ะ', ' ', 'รู้', 'เลย', 'นะคะ', 'ทำไม', 'ประเทศ', 'ไทย', 'ยัง', 'ไม่', 'เจริญ']),
        6]], dtype=object)

In [12]:
from keras.preprocessing.text import Tokenizer

In [13]:
#เตรียมสร้าง dict โดยการวิ่งเข้าไปใส่ลำดับเป็นอันๆ
tokenizer = Tokenizer() # ตัวใส่ลำดับให้กับข้อมูลของเรา 
tokenizer.fit_on_texts(train_array[:,0]) #ใส่ลำดับด้วยการวิ่งเข้าไปที่ array แต่ละแถวแล้วใส่ลำดับให้แต่ละคำ
tokenizer.word_index

{' ': 1,
 'ไม่': 2,
 'เลย': 3,
 'ได้': 4,
 'ก็': 5,
 'ไป': 6,
 'มี': 7,
 'จะ': 8,
 'นะ': 9,
 'คน': 10,
 'มา': 11,
 'แล้ว': 12,
 'ๆ': 13,
 'ที่': 14,
 'เป็น': 15,
 'ให้': 16,
 'ว่า': 17,
 'มัน': 18,
 'มึง': 19,
 'มาก': 20,
 'ทำ': 21,
 'อยาก': 22,
 'ดู': 23,
 'เขา': 24,
 'หรอ': 25,
 'นี้': 26,
 'แต่': 27,
 'เอา': 28,
 'ยัง': 29,
 'กู': 30,
 'อยู่': 31,
 'อะไร': 32,
 'กับ': 33,
 'นี่': 34,
 'แบบ': 35,
 'กัน': 36,
 'ใคร': 37,
 'ดี': 38,
 'ครับ': 39,
 'แบบนี้': 40,
 'พวก': 41,
 'ใน': 42,
 'ค่ะ': 43,
 '  ': 44,
 'ของ': 45,
 'รู้': 46,
 'อ่ะ': 47,
 'นั้น': 48,
 'เห็น': 49,
 'คิด': 50,
 'คือ': 51,
 'อีก': 52,
 'อย่า': 53,
 'หน้า': 54,
 'ตัวเอง': 55,
 'ถ้า': 56,
 'เรา': 57,
 'ต้อง': 58,
 'ไง': 59,
 'อี': 60,
 'โง่': 61,
 'แค่': 62,
 'จริงๆ': 63,
 'ชอบ': 64,
 'บ้าง': 65,
 'ขนาด': 66,
 'แม่': 67,
 'จ๊ะ': 68,
 'อย่าง': 69,
 'คุณ': 70,
 'นั่น': 71,
 'ด้วย': 72,
 'เรื่อง': 73,
 'จ้า': 74,
 'เธอ': 75,
 'หรือ': 76,
 'พูด': 77,
 'และ': 78,
 'เหมือน': 79,
 'เอง': 80,
 'มั้ย': 81,
 'สมอง': 82,
 'คนอื่น':

In [14]:
#เก็บลำดับของแต่ละคำเอาไว้ใช้วิเคราะห์ ขั้นตอนนี้จะได้ dict มาหนึ่งอันแล้ว
dictword = tokenizer.word_index #นำคำที่ใส่ index แล้วทำเป็น dict ต่อไป
(pd.DataFrame.from_dict(data=dictword, orient='index').to_csv('dict_file.csv', header=True)) #จะรับคำใหม่ๆเข้ามาแล้วเขียนทับลงไปที่ไฟล์เดิม

In [17]:
pd.read_csv('dict_file.csv')

Unnamed: 0     0
0                    1
1            ไม่     2
2            เลย     3
3            ได้     4
4             ก็     5
...          ...   ...
6913         เอะ  6914
6914      ลูกพี่  6915
6915     ชักโครก  6916
6916  ทำประโยชน์  6917
6917        คุณๆ  6918

[6918 rows x 2 columns]

# Supervised Learning + Auto label

In [18]:
# class 6 class สำหรับเป็นเฉลยให้โมเดล
def classify_word(y):
    if x==1:
        classify_word = np.array([1,0,0,0,0,0]) # คำบูลลี่ประเภทที่ 1 ปกติ
    elif x==2:
        classify_word = np.array([0,1,0,0,0,0])# คำบูลลี่ประเภทที่ 2 โดดเดี่ยว
    elif x==3:
        classify_word = np.array([0,0,1,0,0,0])# คำบูลลี่ประเภทที่ 3 ขู่ คุกคาม
    elif x==4:
        classify_word = np.array([0,0,0,1,0,0])# คำบูลลี่ประเภทที่ 4 แฉ
    elif x==5:
        classify_word = np.array([0,0,0,0,1,0])# คำบูลลี่ประเภทที่ 5 ดูถูกเหยียดหยาม
    else:
        classify_word = np.array([0,0,0,0,0,1])# คำบูลลี่ประเภทที่ 6 ป่วน
    return classify_word    

In [19]:
dict_fileWord = pd.read_csv('dict_file.csv')
print(dict_fileWord.shape) # โครงสร้างของ dict ที่เราทำการตัดคำมาใส่ index 
print(dict_fileWord) #ข้อมูลที่อยู่ข้างใน dict

(6918, 2)
      Unnamed: 0     0
0                    1
1            ไม่     2
2            เลย     3
3            ได้     4
4             ก็     5
...          ...   ...
6913         เอะ  6914
6914      ลูกพี่  6915
6915     ชักโครก  6916
6916  ทำประโยชน์  6917
6917        คุณๆ  6918

[6918 rows x 2 columns]


In [20]:
train['toxic']

0       1
1       1
2       1
3       1
4       1
       ..
5395    6
5396    6
5397    6
5398    6
5399    6
Name: toxic, Length: 5400, dtype: int64

In [21]:
import numpy as np

y = []
for x in train['toxic']:
    y.append(classify_word(x))
y = np.array(y)
print(y)
 

[[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 ...
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]]


In [22]:
# ทำการ mapping คำที่ตัดแล้วใน dict กับ train_array เพราะตอนแรกเราทำ index ให้กับ dict อย่างเดียว
sequence = list()

for n in train_array[:,0]: #วนเข้าในข้อความแต่ละแถว
    
    sequenceTemp = list()
    
    for w in n:#นำคำที่ได้ออกมาเพื่อนำไปจับคู่
        
        count=0
        
        for x in dict_fileWord['Unnamed: 0']:#วนเข้าไปใน dict เพื่อหาตำแหน่งที่ตรงกับคำนั้นๆจดหมดทั้ง dict
            
            count=count+1
            
            if x==w:#
                
                sequenceTemp.append(count)#นำตำแหน่งไปใช้เป็นตัวแทนของคำนั้นๆ
                break #ต้องใส่ด้วยเวลาเจอแล้วมันจะได้หลุดจากลูป แล้วไปหาคำถัดไปเลย
                
    sequence.append(sequenceTemp)    

In [41]:
word_sequence = np.array(sequence)
word_sequence
tmp = []
for i in word_sequence:
    tmp.append(len(i))
maxLen = max(tmp)

In [42]:
from keras.preprocessing.sequence import pad_sequences
x = pad_sequences(word_sequence, maxlen=maxLen, padding="post")
print(x.shape)

print(y.shape)
train.shape

(5400, 43)
(5400, 6)


(5400, 2)

In [43]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [44]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(3780, 43)
(1620, 43)
(3780, 6)
(1620, 6)


In [45]:
from tensorflow.python.keras.layers import *
from tensorflow.python.keras import Sequential
# Model
model = Sequential() #ลำดับ


model.add(Embedding(6919,64, input_length=maxLen))#4185 +1 size of dict_file

#CNN
model.add(Conv1D(64, 3, activation='relu'))
model.add(Dropout(0.25))
model.add(MaxPooling1D())
# model.add(Dropout(0.8))
# model.add(Dense(32, activation='relu'))
model.add(Flatten())

#RNN
model.add(Dense(16, activation='relu'))
# model.add(Dropout(0.8))
model.add(Dense(6, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])

In [46]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 43, 64)            442816    
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 41, 64)            12352     
_________________________________________________________________
dropout_1 (Dropout)          (None, 41, 64)            0         
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 20, 64)            0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1280)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 16)                20496     
_________________________________________________________________
dense_3 (Dense)              (None, 6)                

In [47]:
train_model = model.fit(x_train, y_train, 
                  batch_size=64,
                  epochs=5,
                  verbose=2 , validation_data=(x_test, y_test)) 

Epoch 1/5
60/60 - 1s - loss: 1.7873 - categorical_accuracy: 0.1907 - val_loss: 1.7790 - val_categorical_accuracy: 0.2253
Epoch 2/5
60/60 - 1s - loss: 1.6945 - categorical_accuracy: 0.3085 - val_loss: 1.6413 - val_categorical_accuracy: 0.3105
Epoch 3/5
60/60 - 1s - loss: 1.4173 - categorical_accuracy: 0.4397 - val_loss: 1.5316 - val_categorical_accuracy: 0.3957
Epoch 4/5
60/60 - 1s - loss: 1.1058 - categorical_accuracy: 0.6138 - val_loss: 1.4212 - val_categorical_accuracy: 0.4500
Epoch 5/5
60/60 - 1s - loss: 0.8434 - categorical_accuracy: 0.6960 - val_loss: 1.4721 - val_categorical_accuracy: 0.4290


In [48]:
import plotly.graph_objs as go
from plotly import tools
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
def create_trace(x,y,ylabel,color):
        trace = go.Scatter(
            x = x,y = y,
            name=ylabel,
            marker=dict(color=color),
            mode = "markers+lines",
            text=x
        )
        return trace
def plot_accuracy_and_loss(train_model):
    hist = train_model.history
    acc = hist['categorical_accuracy']
    val_acc = hist['val_categorical_accuracy']
    loss = hist['loss']
    val_loss = hist['val_loss']
    epochs = list(range(1,len(acc)+1))
    
    trace_ta = create_trace(epochs,acc,"Training accuracy", "Green")
    trace_va = create_trace(epochs,val_acc,"Validation accuracy", "Red")
    trace_tl = create_trace(epochs,loss,"Training loss", "Blue")
    trace_vl = create_trace(epochs,val_loss,"Validation loss", "Magenta")
   
    fig = tools.make_subplots(rows=1,cols=2, subplot_titles=('Training and validation accuracy',
                                                             'Training and validation loss'))
    fig.append_trace(trace_ta,1,1)
    fig.append_trace(trace_va,1,1)
    fig.append_trace(trace_tl,1,2)
    fig.append_trace(trace_vl,1,2)
    fig['layout']['xaxis'].update(title = 'Epoch')
    fig['layout']['xaxis2'].update(title = 'Epoch')
    fig['layout']['yaxis'].update(title = 'Accuracy', range=[0,1])
    fig['layout']['yaxis2'].update(title = 'Loss', range=[0,1])

    iplot(fig, filename='accuracy-loss')

In [49]:
plot_accuracy_and_loss(train_model)

c:\python38\lib\site-packages\plotly\tools.py:461: DeprecationWarning:

plotly.tools.make_subplots is deprecated, please use plotly.subplots.make_subplots instead



In [50]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 1.472123384475708
Test accuracy: 0.42901235818862915


In [51]:
model.save('ver1.h5')

In [52]:
#ฟังก์ชั่น ที่รวมการ normalize ด้วยวิธีการทั้งหมดเอาไว้ เข้าทีเดียวจบ
def getinput(train):
    list_word = []
    proc = word_tokenize(train, engine='newmm')
    list_word.append(proc) #ตัดคำใหม่ที่รับเข้ามาเสร็จใส่list
    
    sequence = list()
    for n in list_word: #ลูปเปลี่ยน คำ string ที่ตัดมาแปลงเป็นตัวเลข
        sequenceTemp = list() 
        for w in n:
            count=0
            for x in dict_fileWord['Unnamed: 0']: #ลูปเทียบdictคำ
                count=count+1
                if x==w:
                    sequenceTemp.append(count)
                    break
        sequence.append(sequenceTemp)  
    test = np.array(sequence)

    testX = pad_sequences(test, maxlen=maxLen, padding="post") #input_length=105
    return testX

In [53]:
test_documents = pd.read_csv ('non_labelData.csv')
test_documents

word  toxic1  toxic2  toxic3
0         ร้านนี้ให้น้อยครับท้องไม่แน่นแต่เป้าแน่นมาก     NaN     NaN     NaN
1   เห็นสาวๆเป็นไม่ได้ ถ้าลองเป็นป้าๆ ใส่แบบนี้จะไ...     NaN     NaN     NaN
2               คุ้มนะสำหรับผม..กินไปมองคนทำไป..อร่อย     NaN     NaN     NaN
3                                 เห็นแล้วจะอ้วก ขมคอ     NaN     NaN     NaN
4                  เปิดบรรยายมาซะกูไม่กล้าแดกเลยครับ      NaN     NaN     NaN
5                                    ดูท่าดูดพี่เขาซิ     NaN     NaN     NaN
6                   ขายอะไรอะ ก๋วยเตี้ยวหรือเรือนร่าง     NaN     NaN     NaN
7   แหมขยันทำงานจังเลยนะค้า กลัวเงินทำศพคนในตระกูล...     NaN     NaN     NaN
8    คล้ายๆเลยนะคะ ปราบโกงแต่โกงเองน่าสมเพชสุด เป็นงง     NaN     NaN     NaN
9   พูดไรไว้ทำได้บ้างยังเอ่ย เป็นทหารดีๆ สาระแนลงน...     NaN     NaN     NaN
10             ว้ายยอมรับว่าโกงหรอคะ ขออนุญาตยกหีบหนี     NaN     NaN     NaN
11  ที่ร้องว่าจะไม่โกงแม่งก็หนีคดี เยอะแยะ แล้วแต่...     NaN     NaN     NaN
12  อ้าว...แล้วตรงไหนยอมรับว่าโกง ขี้แพ้ตาลายป่ะ ก...     NaN     NaN     NaN
13  กระจอกนี่เอาไว้ใช้กับหน้าที่การงานตัวเองดีกว่า...     NaN     NaN     NaN
14  รู้ตัวว่าเป็นขี้ข้าพิทักษ์ นกม.ส้นตีน แบบนี้ก็...     NaN     NaN     NaN
15  เก็บไว้ปลอบใจตัวเองดีกว่านะคะ55555555555555555...     NaN     NaN     NaN
16  คำว่าส้นตีนนี่ก็เลี่ยงไม่ได้เลยค่ะ ยกคำนี้ให้ท...     NaN     NaN     NaN
17      ชั้นอยู่ในยุคที่สลิ่มบอกว่าฝ่ายค้านเปลืองภาษี     NaN     NaN     NaN
18        อย่าบอกว่าไม่ใช่หน้าที่ เพราะทำได้แค่เห่านะ     NaN     NaN     NaN
19  จริงๆคุณพี่ไม่ควรโง่ ขนาดนี้ เอ็นดูจังเลยโว้ย5...     NaN     NaN     NaN
20  ก็เนี่ยไล่ให้ไปเปิดดูหน้าที่ฝ่ายค้านอยู่ไงคะ โ...     NaN     NaN     NaN
21   มีปัญญาจ่ายหรอคะ ดูทรงแล้วก็คงไม่พ้นเบิกเงินภาษี     NaN     NaN     NaN
22  ปาดน้ำตาไปรับแขกต่อ...ชั่งเค้าเถอะค่ะ เค้าน่าจ...     NaN     NaN     NaN
23  คนเริ่มแท็กนี้บ่งบอกเลยนะว่ามารยาทไม่มี #แม่มึ...     NaN     NaN     NaN
24                       รู้จักทหารเสือราชินีป่าว อุบ     NaN     NaN     NaN
25           จริง ไม่ชอบเลย เราไม่โอเคกะแท็คนี้มากๆอะ     NaN     NaN     NaN
26                       บ่งบอกถึงความไร้มารยาทมากค่ะ     NaN     NaN     NaN
27                              อะจ้าลอยแพกันเก่งจริง     NaN     NaN     NaN
28         ผู้ใหญ่ขี้ขลาด หรือ เด็กไม่มีสติ ต้องคิดนะ     NaN     NaN     NaN
29                           ว้าวซ่า สลิ่มเกลื่อนแท็ก     NaN     NaN     NaN
30                  ไปดูล่าสุดธรรมศาสตร์ฟาดกันเองคิคิ     NaN     NaN     NaN
31            ขอ how to วิธีคุยกับสลิ่มให้รู้เรื่องที     NaN     NaN     NaN
32                  เป็นสลิ่มได้ แต่อย่าลืมความเป็นคน     NaN     NaN     NaN
33  ขอให้พระเจ้าตาก สาปแช่งพวกที่คิดจะล้มล้างสถาบั...     NaN     NaN     NaN

In [54]:
# #ฟังก์ชั่น
# list_label = []

# for x in test_documents['word']:
    
#     test=getinput(x)
#     # print(test)
#     ynew = model.predict(test)
# #     print(ynew[0])
#     list_=[]
    
#     for x in ynew[0]:
#         list_.append(x)
# #     print('#### - = ',list_)
#     max_ = list_.index(max(list_))
#     list_label.append(max_+1)
    
# print(list_label,' lenght :',len(list_label))

In [55]:
# x = [0.9,0.81,0.82,0,0,0]
# max_x = max(x)
# tenper_max_x = max_x * 0.9
# for i in x:
#     if(i>=tenper_max_x ):
#         print(i)
    
    

In [56]:
# กระบวนการหาผลลัพธ์ เตรียมใส label อัตโนมัติ

label_toxic1=[]
label_toxic2=[]
label_toxic3=[]

for x in test_documents['word']:
    
    list_label_toxic = [] #ตำแหน่งที่เป็น multilabel
    
    test=getinput(x)
    # print(test)
    ynew = model.predict(test)
    yn = []
    
    for b in ynew[0]:
        num_per = '%.4f' % b
        yn.append(num_per)
    #  print(ynew[0])
    max_ynew = max(ynew[0][:])
    print('max :-- ','%.4f' % max_ynew)
    tenPer_max_ynew = max_ynew * 0.9
    print('tenper --','%.4f' % tenPer_max_ynew)
    print('result_predict :====',yn)
    
    
    list_label=[] #เก็บค่าที่เป็น Multilabel ไว้ที่นี้
    for i in yn:
#         print('multilabel :++++++++++++',i)
        if(i >= '%.4f' %tenPer_max_ynew ):
            list_label.append(i)
    print('ผลลัพธ์จากการทำนาย Multilabel ::::::::::',list_label)
    
#     เก็บตำแหน่งที่เป็น multilabel โดยการเทียบกับ yn
    for ii in list_label:
        count = 0 
        for iii in yn:
            count+=1
            if(ii == iii):
                list_label_toxic.append(count)
                break
    print('ตำแหน่งของ Multilabel จากที่ทำนาย ::::::::::',list_label_toxic)
    
    count_j=0
    count_len=0
    for j in list_label_toxic:# มีขนาดตามตำแหน่งที่รับมา
        count_j+=1
        
        if(count_j==1):
            print('Index_multilabel::::::::::',list_label_toxic[0],'lenght :::: 1')
            label_toxic1.append(list_label_toxic[0])
            count_len=1

        if(count_j==2):
            print('Index_multilabel::::::::::',list_label_toxic[0:2],'lenght :::: 2')
            label_toxic2.append(list_label_toxic[1])
            count_len=2

        if(count_j==3):
            print('Index_multilabel::::::::::',list_label_toxic[0:3],'lenght :::: 3')
            label_toxic3.append(list_label_toxic[2])
            count_len=3

# แทนที่ตำแหน่งที่ไม่มีด้วย 0
    if( count_len==1):
        label_toxic2.append(0)
        label_toxic3.append(0)
    if( count_len==2):
        label_toxic3.append(0)
#    ตรวจตำแหน่งอีกรอบด้วยตาตามแนวตั้ง     
    print(label_toxic1,label_toxic2,label_toxic3) 

max :--  0.3743
tenper -- 0.3369
result_predict :==== ['0.2962', '0.1079', '0.0942', '0.3743', '0.0520', '0.0753']
ผลลัพธ์จากการทำนาย Multilabel :::::::::: ['0.3743']
ตำแหน่งของ Multilabel จากที่ทำนาย :::::::::: [4]
Index_multilabel:::::::::: 4 lenght :::: 1
[4] [0] [0]
max :--  0.4072
tenper -- 0.3664
result_predict :==== ['0.0419', '0.0899', '0.1907', '0.4072', '0.0691', '0.2012']
ผลลัพธ์จากการทำนาย Multilabel :::::::::: ['0.4072']
ตำแหน่งของ Multilabel จากที่ทำนาย :::::::::: [4]
Index_multilabel:::::::::: 4 lenght :::: 1
[4, 4] [0, 0] [0, 0]
max :--  0.4488
tenper -- 0.4040
result_predict :==== ['0.4488', '0.1431', '0.0521', '0.2580', '0.0535', '0.0444']
ผลลัพธ์จากการทำนาย Multilabel :::::::::: ['0.4488']
ตำแหน่งของ Multilabel จากที่ทำนาย :::::::::: [1]
Index_multilabel:::::::::: 1 lenght :::: 1
[4, 4, 1] [0, 0, 0] [0, 0, 0]
max :--  0.4623
tenper -- 0.4161
result_predict :==== ['0.1174', '0.4623', '0.0229', '0.0655', '0.1660', '0.1659']
ผลลัพธ์จากการทำนาย Multilabel :::::::::: ['0.

max :--  0.5122
tenper -- 0.4609
result_predict :==== ['0.0606', '0.5122', '0.0076', '0.0313', '0.2374', '0.1510']
ผลลัพธ์จากการทำนาย Multilabel :::::::::: ['0.5122']
ตำแหน่งของ Multilabel จากที่ทำนาย :::::::::: [2]
Index_multilabel:::::::::: 2 lenght :::: 1
[4, 4, 1, 2, 2, 3, 2, 4, 1, 5, 4, 4, 6, 5, 5, 2, 5, 2, 2, 2, 5, 2, 5, 2, 2, 2, 1, 1, 2] [0, 0, 0, 0, 6, 0, 0, 0, 4, 0, 6, 0, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 2, 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
max :--  0.4055
tenper -- 0.3649
result_predict :==== ['0.0577', '0.4055', '0.0554', '0.0862', '0.1311', '0.2642']
ผลลัพธ์จากการทำนาย Multilabel :::::::::: ['0.4055']
ตำแหน่งของ Multilabel จากที่ทำนาย :::::::::: [2]
Index_multilabel:::::::::: 2 lenght :::: 1
[4, 4, 1, 2, 2, 3, 2, 4, 1, 5, 4, 4, 6, 5, 5, 2, 5, 2, 2, 2, 5, 2, 5, 2, 2, 2, 1, 1, 2, 2] [0, 0, 0, 0, 6, 0, 0, 0, 4, 0, 6, 0, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [57]:
len(label_toxic1)

34

In [58]:
len(label_toxic2)

34

In [59]:
len(label_toxic3)

34

In [60]:
label_toxic3

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [61]:
# output complete label
# for boom
df = pd.DataFrame({'word': test_documents['word'],
                                'toxic1': label_toxic1,
                                'toxic2': label_toxic2,
                                'toxic3': label_toxic3})

df.to_csv('new_csv.csv',index=False,encoding='utf-8-sig')
label_documents = pd.read_csv ('new_csv.csv')

label_documents

word  toxic1  toxic2  toxic3
0         ร้านนี้ให้น้อยครับท้องไม่แน่นแต่เป้าแน่นมาก       4       0       0
1   เห็นสาวๆเป็นไม่ได้ ถ้าลองเป็นป้าๆ ใส่แบบนี้จะไ...       4       0       0
2               คุ้มนะสำหรับผม..กินไปมองคนทำไป..อร่อย       1       0       0
3                                 เห็นแล้วจะอ้วก ขมคอ       2       0       0
4                  เปิดบรรยายมาซะกูไม่กล้าแดกเลยครับ        2       6       0
5                                    ดูท่าดูดพี่เขาซิ       3       0       0
6                   ขายอะไรอะ ก๋วยเตี้ยวหรือเรือนร่าง       2       0       0
7   แหมขยันทำงานจังเลยนะค้า กลัวเงินทำศพคนในตระกูล...       4       0       0
8    คล้ายๆเลยนะคะ ปราบโกงแต่โกงเองน่าสมเพชสุด เป็นงง       1       4       0
9   พูดไรไว้ทำได้บ้างยังเอ่ย เป็นทหารดีๆ สาระแนลงน...       5       0       0
10             ว้ายยอมรับว่าโกงหรอคะ ขออนุญาตยกหีบหนี       4       6       0
11  ที่ร้องว่าจะไม่โกงแม่งก็หนีคดี เยอะแยะ แล้วแต่...       4       0       0
12  อ้าว...แล้วตรงไหนยอมรับว่าโกง ขี้แพ้ตาลายป่ะ ก...       6       0       0
13  กระจอกนี่เอาไว้ใช้กับหน้าที่การงานตัวเองดีกว่า...       5       0       0
14  รู้ตัวว่าเป็นขี้ข้าพิทักษ์ นกม.ส้นตีน แบบนี้ก็...       5       0       0
15  เก็บไว้ปลอบใจตัวเองดีกว่านะคะ55555555555555555...       2       6       0
16  คำว่าส้นตีนนี่ก็เลี่ยงไม่ได้เลยค่ะ ยกคำนี้ให้ท...       5       0       0
17      ชั้นอยู่ในยุคที่สลิ่มบอกว่าฝ่ายค้านเปลืองภาษี       2       0       0
18        อย่าบอกว่าไม่ใช่หน้าที่ เพราะทำได้แค่เห่านะ       2       0       0
19  จริงๆคุณพี่ไม่ควรโง่ ขนาดนี้ เอ็นดูจังเลยโว้ย5...       2       6       0
20  ก็เนี่ยไล่ให้ไปเปิดดูหน้าที่ฝ่ายค้านอยู่ไงคะ โ...       5       0       0
21   มีปัญญาจ่ายหรอคะ ดูทรงแล้วก็คงไม่พ้นเบิกเงินภาษี       2       0       0
22  ปาดน้ำตาไปรับแขกต่อ...ชั่งเค้าเถอะค่ะ เค้าน่าจ...       5       0       0
23  คนเริ่มแท็กนี้บ่งบอกเลยนะว่ามารยาทไม่มี #แม่มึ...       2       0       0
24                       รู้จักทหารเสือราชินีป่าว อุบ       2       0       0
25           จริง ไม่ชอบเลย เราไม่โอเคกะแท็คนี้มากๆอะ       2       0       0
26                       บ่งบอกถึงความไร้มารยาทมากค่ะ       1       0       0
27                              อะจ้าลอยแพกันเก่งจริง       1       2       0
28         ผู้ใหญ่ขี้ขลาด หรือ เด็กไม่มีสติ ต้องคิดนะ       2       0       0
29                           ว้าวซ่า สลิ่มเกลื่อนแท็ก       2       0       0
30                  ไปดูล่าสุดธรรมศาสตร์ฟาดกันเองคิคิ       6       0       0
31            ขอ how to วิธีคุยกับสลิ่มให้รู้เรื่องที       2       0       0
32                  เป็นสลิ่มได้ แต่อย่าลืมความเป็นคน       2       0       0
33  ขอให้พระเจ้าตาก สาปแช่งพวกที่คิดจะล้มล้างสถาบั...       3       0       0

In [62]:
# # for ozone
# df = pd.DataFrame({'word': test_documents['word'],
#                                 'toxic1': label_toxic1,
#                                 'toxic2': label_toxic2,
#                                 'toxic3': label_toxic3})

# df.to_csv('new_csv.csv',index=False,encoding='utf-8-sig')
# label_documents = pd.read_csv ('new_csv.csv')

# label_documents